### ISSUE TITLE
Allow for something other than MDL icons for the menu button.

### ISSUE THREAD

**Issue by Lattyware** [debois/elm-mdl#165]
I am currently porting a project ([massivedecks](https://github.com/Lattyware/massivedecks)) to use elm-mdl (from muicss integrated manually) - we used fontawesome for icons in the past, and the material design icon set is missing a number of icons used, so I have stuck with fontawesome and simply not included the MDL icons - that all seems fine and is working well, except the menu, which appears to only have support for MDL icons for the menu button.

It would unblock us to allow arbitrary content for the menu button as a replacement for the icon (I can also see this holding value for those that want text instead of an icon, for example). Otherwise we have to include two icon fonts, when one would do fine.

**Comment by OvermindDL1** [comment]
As a work-around for now in your site CSS you can override the those to make them invisible and add an :after element that adds whatever you need for a font (via some parent div with, say, a `data-myicon="somefontawesome"` value or so, can set it with something like:
```css
some[data-myicon] > selector {
  make it invisible however you want, like width=0px should work and put the :after in the right place
}

some[data-myicon] > selector:after {
  content: attr(data-badge);
}
```
I doubt that is the right setting or if the attr works from a parent, but there is always some way to do it via css.
