### ISSUE TITLE
Floating label does not stay floating when textfield has value

### ISSUE THREAD

**Issue by nilsga** [debois/elm-mdl#278]
When using a textfield with a floating label, the label should float when you enter a value, and the label should stay floating when the field loses focus. With elm-mdl, in some cases this does not seem to be the case, as can be viewed on the live demo for the framework: at https://debois.github.io/elm-mdl/#textfields

Choose the "Multi-line textfield with character limit" demo, enter a value in the textfield and start dragging the slider below the textfield.

**Comment by nilsga** [comment]
It seems to be related to using the `Options.onInput` event handler. When removing this event handler, the floating label sticks as it should.

**Comment by OvermindDL1** [comment]
Sounds like the elm-mdl and user 'input' event handlers are not being combined?

**Comment by nilsga** [comment]
Most likely, yes. Debugging reveals that the default handler is certainly not invoked when registering an `onInput` handler on the text field. The documentation said something about having to handle this manually with the `Options.dispatch` method, but it also says that

> The `render` function does all this automatically. If you are calling `render`,
you do not need this property.

So I'm not sure what to believe.

**Comment by zainhoda** [comment]
I also encountered this problem and despite what the documentation says about 

> The render function does all this automatically. If you are calling render, you do not need this property.

```
Textfield.render Mdl [1] model.mdl
                           [ Textfield.label model.placeholder
                           , Textfield.floatingLabel
                           , Textfield.text_
                           , Options.onInput (\str -> (UserTyped str))
                           , Textfield.error ("No match for " ++ model.currentText)
                               |> Options.when (List.length model.options == 0)
                           , Options.dispatch Batch
                           ]
                           []
```

I ended up needing to use Options.dispatch and then handling the batch in my update function.

**Comment by nilsga** [comment]
> I ended up needing to use Options.dispatch and then handling the batch in my update function.

Would you mind sharing your solution? I tried to do this, but didn't quite understand from the fragments in the documentation how to use `Options.dispatch` and batching.

**Comment by zainhoda** [comment]
I added `Batch (List Msg)` to my `Msg` then I added this to my update function:

```
                Batch listOfMsg ->
                        let (finalModel, listOfFx) = List.foldl (\msg -> \(mdl, fxList) ->
                                        let (newModel, newFx) = update msg mdl
                                        in
                                                (newModel, fxList ++ [newFx])
                                       ) (model, []) listOfMsg
                        in
                                (finalModel, Cmd.batch listOfFx)
```

I'm pretty sure there's a more elegant solution than this, but it seems to work. What this will do is it'll apply the update function to the whole list of messages and sequentially update the models. Then it'll batch the list of side effects that are generated by all the update calls in one go.

**Comment by nilsga** [comment]
Thanks, but it doesn't quite work for me it seems. The label stays floating, but only until I start typing in a different textfield. Then the label collapses again. Maybe something is different with my setup. I did try to set the value of the textfield, which did seem to resolve the problem, but it had some other unwanted issues.

**Comment by Matsebassen** [comment]
I'm having the same issue.
It's quite annoying :(

**Comment by astlouisf** [comment]
It seems that when using `Options.onInput` you HAVE to also provide a `Textfield.value` property.

This fixed the problem for me when I encountered it and it also fixed the problem for user anarute on the elm-mdl slack.

**Comment by Matsebassen** [comment]
Ahhh. thanks a lot for the reply!

This fixed it for me as well. For some reason (don't remember why anymore), I was using this code to set the value:
Options.attribute <| value defValue.

It works when I changed it to:
Textfield.value defValue

**Comment by vipentti** [comment]
Indeed, setting the value manually should fix this temporarily.

**Comment by tad-lispy** [comment]
The solution by @astlouisf works very well and is straight forward.

Perhaps the examples on the demo page should demonstrate this. As of now they are not connected to any model and may mislead the reader to think that it's enough to add `onInput` to connect them.  So maybe the examples should all contain both `Options.onInput` and `Textfield.value` attributes.

**Comment by aforemny** [comment]
I will close here. Continuation (and fix) in #333. Thanks for all the input on this!

**Comment by OvermindDL1** [comment]
For note, I'm not even sure 'why' the floating label requires messages in elm, it is pretty trivially done in pure CSS (which I did if anyone wants it).

**Comment by aforemny** [comment]
I would be interested in how you do it in CSS if you have it handy. :)

**Comment by OvermindDL1** [comment]
This is the basic bit of it, it is SCSS, pretty well built for my site hence the lack of classnames except in certain ways:
```css
label {
  color: lighten($black, 5%);
}


input {
  background: linear-gradient(to bottom, $transparent-white 96%, $primary 96%);
  background-position: 50% 0;
  background-repeat: no-repeat;
  background-size: 0 100%;
  border: 0;
  border-bottom: solid 1px $primary;
  min-height: 26px;
  transition: background-size .3s $cubic, box-shadow .3s $cubic;
  will-change: background-size;

  &:valid {
    background-size: 0% 100%;
  }

  &:focus {
    background-size: 100% 100%;
  }
}

.label-group {
  margin: $space-med 4px;
  outline: none;
  padding: 0;
  position: relative;
  user-select: none;

  label {
    padding-left: 2px;
    position: absolute;
    user-select: none;
    width: 100%;
  }
}

.floating-label-group {
  margin: $space-med 4px;
  outline: none;
  padding: 0;
  position: relative;

  label {
    color: $secondary;
    cursor: text;
    left: 0;
    padding-left: 2px;
    position: absolute;
    top: 2px;
    transition: top .3s $cubic, font-size .3s $cubic, color .3s $cubic;
    user-select: none;
    width: 100%;

    &::after {
      transition: content .3s $cubic;
    }
  }

  input,
  .grouping {
    background: linear-gradient(to bottom, $transparent-white 96%, $primary 96%);
    background-color: $primary-inverted;
    padding: 0;
    width: 100%;

    &.grouping {
      display: flex;

      > * {
        flex: 1;
      }
    }

    &:focus + label,
    &:valid + label,
    &[type='date'] + label,
    &[type='time'] + label,
    &[type='datetime-local'] + label,
    &[type='month'] + label,
    &.grouping + label {
      color: $primary;
      font-size: 11px;
      height: $space-small;
      line-height: $space-small;
      top: -$space-small;
      width: 100%;
    }

    &:invalid + label {
      background-color: $accent;
      color: $accent-text;

      &::after {
        content: ' (invalid)';
      }
    }

    &[required]:invalid + label::after {
      content: ' (required)';
    }
  }
}

.lower-label-group {
  margin: $space-med 4px;
  outline: none;
  padding: 0;
  position: relative;

  label {
    bottom: 0;
    color: $secondary;
    cursor: text;
    left: 0;
    padding-left: 2px;
    position: absolute;
    transition: bottom .3s $cubic, font-size .3s $cubic, color .3s $cubic, background-color .3s $cubic;
    user-select: none;
    width: 100%;

    &::after {
      transition: content .3s $cubic;
    }
  }

  input,
  .grouping {
    background: linear-gradient(to bottom, $transparent-white 96%, $primary 96%);
    background-color: $primary-inverted;
    padding: 0;
    width: 100%;

    &.grouping {
      display: flex;

      > * {
        flex: 1;
      }

      > .lower-label-group,
      > .floating-label-group {
        margin: 12px 4px;
      }
    }

    &:focus + label,
    &:valid + label,
    &[type='date'] + label,
    &[type='time'] + label,
    &[type='datetime-local'] + label,
    &[type='month'] + label,
    &.grouping + label {
      background-color: $primary;
      border: solid 1px $primary;
      bottom: -$space-small;
      color: $primary-inverted;
      font-size: 11px;
      height: $space-small;
      line-height: $space-small - 1;
    }

    &:invalid + label {
      background-color: $accent;
      color: $accent-text;

      &::after {
        content: ' (invalid)';
      }
    }

    &[required]:invalid + label::after {
      content: ' (required)';
    }
  }
}
```
I have a lot of refinements for specific input types too like if it is a date select or other things as well so it all works for what I need.  I keep intended to put it all up on github (I have a *lot* of the MDL-like stuff in pure CSS without a single lick of javascript/elm/anything so it can be used anywhere, everything from floating labels to nav's to accordians to tabs to more and more, all pure SCSS).

I have two styles of 'floating things' in the above example, one floats 'above' and looks like MDL, the other floats below into a box (which I find much more readable in certain packed forms for business use).  You can use them like:
```html
    <div class="floating-label-group">
      <%= generic_input type, f, id, inputOpts %>
      <%= label f, id, labelDo, labelOpts %>
      <%= error_tag f, id %>
    </div>
```
(This is EEX templates)
But in general just make a `div` of classname either `"floating-label-group"` or `"lower-label-group"` depending on the style you want, and inside of it make sure to contain an `input` (of whatever form you want though without the rest of the fairly large CSS not all will look quite right, but text should be fine with the above, just fill in the color variables as necessary), and immediately after the input must be the label that is `for`'d to it.  You can have any other elements you want around those, just not between.
